"""
Tests for the Zusatzmodule/Passerelle feature (see
docs/planung/KONZEPT-passerelle-zusatzmodule.md) against the large-scale
and scenario-specific fixtures in tests/fixtures/, generated by
tests/fixtures/generate_fictional_fixtures.py.

Kept separate from test_data_loader.py/test_scheduler.py (which already
cover the general-purpose loader/conflict pipeline against the original,
smaller fixtures) because this file specifically exercises Zusatzmodule
behaviour at a realistic real-world scale and diversity: the "vollstaendig"
fixtures are full-scale fictionalizations of the actual HS26 Bachelor
(1182 rows) and Master (343 rows) catalogs the feature was built and
verified against, not hand-picked excerpts - so a regression that only
shows up with real-world row counts, real Modulart diversity, or the
real "undistinguished parallel offerings" frequency (see
app._has_undistinguished_parallel_offerings) has a fixture that can
actually catch it.

None of this file's fixtures contain any real person's name or real ZHAW
curriculum content - see generate_fictional_fixtures.py's module
docstring for the fictionalization rules and tests/fixtures/
generate_fictional_fixtures.py itself for how they were produced.
"""

import io
from pathlib import Path

import pandas as pd
import pytest

from data_loader import load_schedule_from_dataframe
from export import generate_excel_download, generate_ics_download, prepare_timetable_for_export
from models import Weekday
from scheduler import find_time_conflicts

REAL_BSC_PATH = Path(__file__).resolve().parent.parent / "data" / "real" / "Vorlesungsdaten BSc HS26_P.xlsx"
REAL_MSC_PATH = Path(__file__).resolve().parent.parent / "data" / "real" / "Vorlesungsdaten MSc HS26.xlsx"

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"

BSC_VOLLSTAENDIG_PATH = FIXTURES_DIR / "vorlesungsverzeichnis_bsc_vollstaendig_fiktiv.xlsx"
MSC_VOLLSTAENDIG_PATH = FIXTURES_DIR / "vorlesungsverzeichnis_msc_vollstaendig_fiktiv.xlsx"
KONFLIKT_HAUPTLISTE_PATH = FIXTURES_DIR / "vorlesungsverzeichnis_konflikt_hauptliste_fiktiv.xlsx"
KONFLIKT_ZUSATZLISTE_PATH = FIXTURES_DIR / "vorlesungsverzeichnis_konflikt_zusatzliste_fiktiv.xlsx"
KOLLISION_HAUPTLISTE_PATH = FIXTURES_DIR / "vorlesungsverzeichnis_modulnr_kollision_hauptliste_fiktiv.xlsx"
KOLLISION_ZUSATZLISTE_PATH = FIXTURES_DIR / "vorlesungsverzeichnis_modulnr_kollision_zusatzliste_fiktiv.xlsx"


def _load(path: Path, ist_zusatzmodul: bool = False):
    """Read a fixture the same way app.py's Excel upload branch does
    (header=None, letting data_loader locate the real header row itself)
    and run it through the real loader - never construct ZHAWModule
    objects by hand in this file, since the whole point is exercising the
    full real pipeline against realistic data."""
    raw_df = pd.read_excel(path, header=None, sheet_name="Vorlesungsverzeichnis")
    return load_schedule_from_dataframe(raw_df, ist_zusatzmodul=ist_zusatzmodul)


# --- Fixture files exist ------------------------------------------------

@pytest.mark.parametrize(
    "path",
    [
        BSC_VOLLSTAENDIG_PATH,
        MSC_VOLLSTAENDIG_PATH,
        KONFLIKT_HAUPTLISTE_PATH,
        KONFLIKT_ZUSATZLISTE_PATH,
        KOLLISION_HAUPTLISTE_PATH,
        KOLLISION_ZUSATZLISTE_PATH,
    ],
)
def test_fixture_file_exists(path):
    assert path.exists(), f"Missing fixture: {path.name}. Regenerate with tests/fixtures/generate_fictional_fixtures.py."


# --- Full-scale Bachelor/Zusatzmodule catalog (1182 real rows) ----------

@pytest.fixture(scope="module")
def bsc_modules():
    return _load(BSC_VOLLSTAENDIG_PATH, ist_zusatzmodul=True)


def test_bsc_vollstaendig_loads_almost_every_row(bsc_modules):
    # 1182 raw rows, one genuinely has a malformed time value ("11"
    # instead of "HH:MM") in the real source export - this is a real,
    # pre-existing data-quality issue in the actual HS26 catalog, kept
    # intact by the fictionalization (it doesn't touch Datum/von/bis), so
    # this is also an implicit regression test for the "one bad row
    # doesn't sink the whole import" graceful-degradation behaviour
    # documented in data_loader.py's module docstring.
    assert len(bsc_modules) == 1181


def test_bsc_vollstaendig_source_file_has_no_weekday_column(bsc_modules):
    # Sanity-checks the premise of the next test: if this fixture ever
    # gained a Tag column (e.g. from a future regeneration against a
    # different real export), the derivation test below would stop
    # meaning anything and should be revisited.
    raw_df = pd.read_excel(BSC_VOLLSTAENDIG_PATH, header=None, sheet_name="Vorlesungsverzeichnis")
    header_row = [str(v).strip().lower() for v in raw_df.iloc[2].tolist()]
    assert "tag" not in header_row


def test_bsc_vollstaendig_weekday_derived_for_every_row(bsc_modules):
    # Every one of the ~1181 loaded rows must have a real Weekday enum
    # value (not a placeholder) - proves the datum->wochentag derivation
    # (data_loader.py) works across the *entire* real date range, not
    # just a couple of hand-picked dates.
    assert all(isinstance(m.wochentag, Weekday) for m in bsc_modules)
    weekdays_seen = {m.wochentag for m in bsc_modules}
    # The real semester spans weekday and Saturday sessions (see the real
    # Semester column's "VZ"/"TZ" mix) - expect meaningful spread, not
    # e.g. everything accidentally collapsing onto one weekday due to an
    # off-by-one in the derivation.
    assert len(weekdays_seen) >= 5


def test_bsc_vollstaendig_all_rows_tagged_as_zusatzmodul(bsc_modules):
    assert all(m.ist_zusatzmodul is True for m in bsc_modules)


def test_bsc_vollstaendig_ects_defaults_to_zero(bsc_modules):
    # The real Bachelor export has no ECTS column at all - confirms the
    # "ECTS is the only missing required column -> default to 0" rule
    # (data_loader.py) still applies at full scale, not just to the small
    # hand-built fixture.
    assert all(m.ects == 0 for m in bsc_modules)


def test_bsc_vollstaendig_covers_every_real_modulart(bsc_modules):
    # The real catalog's three Modulart values, confirmed via direct
    # inspection of the source export - if fictionalization or loading
    # ever dropped/mangled Modulart, this would catch it.
    assert {m.modultyp for m in bsc_modules} == {"Pflichtmodul", "Spezialtermin", "Wahlpflichtmodul"}


def test_bsc_vollstaendig_contains_a_fully_labeled_parallel_group(bsc_modules):
    # The real catalog's biggest "labeled" parallel-group pattern: 8 rows
    # at the same date/time/Modul-Nr, each with a distinct "- Gruppe X"
    # suffix (a>h) - a student can meaningfully choose between them. This
    # locks in that the fictionalization's per-base-title mapping (see
    # generate_fictional_fixtures.py's split_title_suffix) doesn't merge
    # or lose any of the 8 distinct suffixes.
    by_slot = {}
    for m in bsc_modules:
        by_slot.setdefault((m.datum, m.startzeit, m.endzeit, m.modul_nr), set()).add(m.modulname)
    largest_group = max(by_slot.values(), key=len)
    assert len(largest_group) == 8
    assert all("Gruppe" in name for name in largest_group)


def test_bsc_vollstaendig_contains_undistinguished_parallel_offerings(bsc_modules):
    # The real catalog's OTHER parallel-offering pattern: same date/time/
    # Modul-Nr/Kurs-Nr/title, but with NO distinguishing suffix at all -
    # only the lecturer differs (see docs/planung/KONZEPT-passerelle-
    # zusatzmodule.md section 8, risk 1 - confirmed in ~47% of the real
    # catalog's same-slot multi-lecturer cases). This is what
    # app._has_undistinguished_parallel_offerings() (not covered by this
    # file - see docs/TESTING-README.md "What isn't covered") detects.
    by_slot: dict[tuple, list] = {}
    for m in bsc_modules:
        by_slot.setdefault((m.datum, m.startzeit, m.endzeit, m.modul_nr, m.kurs_nr, m.modulname), []).append(m)
    undistinguished_groups = [rows for rows in by_slot.values() if len({r.dozierende for r in rows}) > 1]
    assert len(undistinguished_groups) > 0
    assert any(len(rows) >= 3 for rows in undistinguished_groups)


def test_bsc_vollstaendig_no_real_lecturer_names_leaked(bsc_modules):
    # A cheap-but-meaningful safety net (not a substitute for actually
    # diffing against the real file, which isn't available in CI/most
    # dev machines - see data/real/'s .gitignore): every fictional
    # lecturer name in this project's convention is "<Surname> <First
    # name>" built from a small closed pool of obviously-invented
    # surnames (see generate_fictional_fixtures.py's _SURNAMES). If a
    # real name ever leaked through, it would almost certainly not start
    # with one of these.
    fictional_surnames = {
        "Muster", "Beispiel", "Demo", "Platzhalter", "Vorlage", "Fiktiv",
        "Testfall", "Musterfrau", "Musterhaft", "Probeweise",
    }
    surnames_seen = {str(m.dozierende).split(" ")[0] for m in bsc_modules if m.dozierende and m.dozierende != "N/A"}
    assert surnames_seen <= fictional_surnames


# --- Full-scale Master catalog (343 real rows) ---------------------------

@pytest.fixture(scope="module")
def msc_modules():
    return _load(MSC_VOLLSTAENDIG_PATH, ist_zusatzmodul=False)


def test_msc_vollstaendig_loads_almost_every_row(msc_modules):
    # 343 raw rows; the real export's last row is a dateless/timeless
    # "Diverse" placeholder line with no Modul-Nr at all (confirmed via
    # direct inspection of the real file - not a fictionalization
    # artifact), correctly dropped by _sanitize_dataframe()'s "rows
    # without both start/end times aren't schedulable" rule.
    assert len(msc_modules) == 342


def test_msc_vollstaendig_weekday_comes_directly_from_tag_column(msc_modules):
    # Unlike the Bachelor fixture, the Master export DOES have its own
    # "Tag" column - this fixture must never trigger the datum-derivation
    # path at all (that's the Bachelor fixture's job to test). Confirmed
    # indirectly here: every loaded row has a valid, real Weekday - and
    # explicitly by checking the raw header for "Tag".
    raw_df = pd.read_excel(MSC_VOLLSTAENDIG_PATH, header=None, sheet_name="Vorlesungsverzeichnis")
    header_row = [str(v).strip().lower() for v in raw_df.iloc[2].tolist()]
    assert "tag" in header_row
    assert all(isinstance(m.wochentag, Weekday) for m in msc_modules)


def test_msc_vollstaendig_blank_second_column_is_ignored(msc_modules):
    # The real Master export has a genuinely blank second column (between
    # "SG" and "Lehrperson" - see generate_fictional_fixtures.py's
    # blank_column_after="SG"). If _normalize_columns()'s "drop unnamed
    # columns" rule ever regressed, every row would misparse (Lehrperson
    # data would land in the wrong field) and this assertion would fail.
    lecturer_names = {m.dozierende for m in msc_modules}
    assert all(name and name != "N/A" for name in lecturer_names)


def test_msc_vollstaendig_all_rows_tagged_as_main_list(msc_modules):
    assert all(m.ist_zusatzmodul is False for m in msc_modules)


def test_msc_vollstaendig_ects_defaults_to_zero(msc_modules):
    assert all(m.ects == 0 for m in msc_modules)


def test_msc_vollstaendig_covers_multiple_modulart_values(msc_modules):
    # The real Master catalog's Modulart values include a trailing-space
    # variant ("Wahlpflichtmodul " vs "Wahlpflichtmodul") - a genuine
    # real-world data-quality quirk kept intact by fictionalization,
    # useful as-is since ZHAWModule.modultyp doesn't strip/normalize it
    # (it's a free-text display field, not compared against a fixed set).
    modularten = {m.modultyp for m in msc_modules}
    assert len(modularten) >= 4


def test_msc_vollstaendig_semester_range_matches_real_catalog(msc_modules):
    # 2026-08-27 is a real early outlier in the source catalog (an exam
    # review session, "Pruefungseinsicht", scheduled before the semester's
    # regular Tuesday lectures start on 2026-09-15) - kept intentionally
    # to prove the loader doesn't quietly clip or reorder real dates.
    # 2027-01-19 (not the raw file's true latest date, 2027-02-24) is the
    # latest date among *loaded* modules: the row actually dated
    # 2027-02-24 is the same dateless/timeless "Diverse" placeholder row
    # covered by test_msc_vollstaendig_loads_almost_every_row, correctly
    # dropped for having no von/bis - it never reaches this list at all.
    dates = [m.datum for m in msc_modules if m.datum is not None]
    assert min(dates).isoformat() == "2026-08-27"
    assert max(dates).isoformat() == "2027-01-19"


# --- Merged main + Zusatzmodule catalogs (both at full scale) -----------

def test_merged_full_scale_catalogs_produce_no_crash_and_plausible_conflict_count(bsc_modules, msc_modules):
    # This is the closest thing to "what actually happens when a real
    # Passerelle student uploads both real catalogs", short of driving
    # the browser (see docs/TESTING-README.md "What isn't covered" for
    # why app.py itself has no automated coverage): merge both full-scale
    # fixtures exactly like app._recompute_combined_modules() does, and
    # run the real conflict detector over the result. Not asserting an
    # exact conflict count (the two real catalogs' overlap is incidental,
    # not an engineered scenario - see the dedicated Konflikt-Szenario
    # fixtures below for a deterministic assertion) - this test's job is
    # to prove the combined ~1523-row pairwise comparison completes
    # correctly and returns internally consistent results, not to pin an
    # exact number that would be fragile against a future regeneration.
    combined = list(bsc_modules) + list(msc_modules)
    assert len(combined) == len(bsc_modules) + len(msc_modules)

    conflicts = find_time_conflicts(combined)
    for left, right in conflicts:
        # A conflict must always pair a Zusatzmodul row with a main-list
        # row, or two rows from the same list - never report a module
        # against itself, and every pair must genuinely overlap.
        assert left is not right
        overlap_starts = max(left.startzeit, right.startzeit)
        overlap_ends = min(left.endzeit, right.endzeit)
        assert overlap_starts < overlap_ends
        assert left.datum == right.datum or left.wochentag == right.wochentag


# --- Hand-engineered conflict scenario (main vs. Zusatzmodul overlap) ---

def test_konflikt_szenario_detects_the_engineered_overlap():
    main_modules = _load(KONFLIKT_HAUPTLISTE_PATH, ist_zusatzmodul=False)
    zusatz_modules = _load(KONFLIKT_ZUSATZLISTE_PATH, ist_zusatzmodul=True)
    assert len(main_modules) == 2
    assert len(zusatz_modules) == 2

    combined = main_modules + zusatz_modules
    conflicts = find_time_conflicts(combined)

    assert len(conflicts) == 1
    left, right = conflicts[0]
    conflicting_modul_nrs = {left.modul_nr, right.modul_nr}
    assert conflicting_modul_nrs == {"KFH1", "KFZ1"}
    # Exactly one side of the reported conflict must be the Zusatzmodul -
    # this is the actual end-to-end proof that a Passerelle student's
    # supplementary module gets checked against their main schedule, not
    # just that *some* conflict was found.
    assert {left.ist_zusatzmodul, right.ist_zusatzmodul} == {True, False}


def test_konflikt_szenario_non_overlapping_pair_is_not_flagged():
    main_modules = _load(KONFLIKT_HAUPTLISTE_PATH, ist_zusatzmodul=False)
    zusatz_modules = _load(KONFLIKT_ZUSATZLISTE_PATH, ist_zusatzmodul=True)
    combined = main_modules + zusatz_modules
    conflicts = find_time_conflicts(combined)

    reported_modul_nrs = {m.modul_nr for pair in conflicts for m in pair}
    assert "KFH2" not in reported_modul_nrs
    assert "KFZ2" not in reported_modul_nrs


def test_konflikt_szenario_weekday_derivation_matches_across_lists():
    # KFH1 (main, has an explicit "Di" Tag column value) and KFZ1
    # (Zusatzmodul, weekday derived from datum, no Tag column) both fall
    # on 2026-09-15 - a Tuesday. If the derivation were off by even one
    # day, find_time_conflicts() would never compare them at all (see
    # scheduler._same_occurrence's date-then-weekday matching) and the
    # conflict test above would fail for a much more confusing reason
    # than "weekdays don't match" - this test isolates that specific
    # failure mode.
    main_modules = _load(KONFLIKT_HAUPTLISTE_PATH, ist_zusatzmodul=False)
    zusatz_modules = _load(KONFLIKT_ZUSATZLISTE_PATH, ist_zusatzmodul=True)
    kfh1 = next(m for m in main_modules if m.modul_nr == "KFH1")
    kfz1 = next(m for m in zusatz_modules if m.modul_nr == "KFZ1")
    assert kfh1.wochentag == kfz1.wochentag == Weekday.TUESDAY


# --- Hand-engineered Modul-Nr collision scenario -------------------------

def test_modulnr_kollision_both_rows_survive_independently():
    # See docs/planung/KONZEPT-passerelle-zusatzmodule.md section 8, risk
    # 2 (precision-corrected after the Phase 1 re-review): the loader
    # itself must never silently drop or merge a Modul-Nr collision
    # between the two lists - both rows are valid, independent
    # ZHAWModule objects, distinguished only by ist_zusatzmodul. Whether
    # the *UI* groups them into one checkbox (it currently does, in
    # app.py - not covered by this file) is a separate, already-documented
    # concern; this test only pins the data-layer contract.
    main_modules = _load(KOLLISION_HAUPTLISTE_PATH, ist_zusatzmodul=False)
    zusatz_modules = _load(KOLLISION_ZUSATZLISTE_PATH, ist_zusatzmodul=True)

    assert len(main_modules) == 1
    assert len(zusatz_modules) == 1
    assert main_modules[0].modul_nr == zusatz_modules[0].modul_nr == "KOL1"
    assert main_modules[0].ist_zusatzmodul is False
    assert zusatz_modules[0].ist_zusatzmodul is True
    # Genuinely distinct rows (different Anlassbezeichnung/date/lecturer)
    # despite the shared Modul-Nr - confirms the collision is real and
    # not an accidental duplicate row.
    assert main_modules[0].modulname != zusatz_modules[0].modulname
    assert main_modules[0].datum != zusatz_modules[0].datum


# --- Cross-catalog Modul-Nr namespace property ---------------------------

def test_full_scale_catalogs_have_no_modul_nr_overlap(bsc_modules, msc_modules):
    # Documents (and locks in, for these fixtures specifically) the
    # empirical finding behind docs/planung/KONZEPT-passerelle-
    # zusatzmodule.md section 8, risk 2: verified against the real HS26
    # data that the Bachelor and Master Modul-Nr namespaces never
    # collide, which is why that risk was assessed as theoretical rather
    # than fixed in code. generate_fictional_fixtures.py's per-letter-
    # prefix mapping preserves this property (each real prefix maps to
    # exactly one fictional prefix, and the two catalogs' real prefixes
    # were already disjoint) - if a future regeneration ever broke that,
    # this would catch it.
    # `None` is excluded deliberately: both real catalogs legitimately
    # have a handful of rows with no Modul-Nr at all (e.g. general-notice
    # rows like an exam-review session) - that's "no module", not a
    # collision, and would otherwise make this assertion fail for a
    # reason unrelated to what it's actually checking.
    bsc_modul_nrs = {m.modul_nr for m in bsc_modules} - {None}
    msc_modul_nrs = {m.modul_nr for m in msc_modules} - {None}
    assert bsc_modul_nrs.isdisjoint(msc_modul_nrs)


# --- Export at realistic scale -------------------------------------------

def test_excel_export_at_full_scale_includes_quelle_column(bsc_modules, msc_modules):
    combined = list(msc_modules) + list(bsc_modules)
    export_df = prepare_timetable_for_export(combined)
    assert len(export_df) == len(combined)
    assert "Quelle" in export_df.columns
    assert (export_df["Quelle"] == "Hauptliste").sum() == len(msc_modules)
    assert (export_df["Quelle"] == "Zusatzmodul").sum() == len(bsc_modules)

    # Doesn't just build the DataFrame - actually renders it to a real
    # .xlsx at ~1500 rows, matching what a Passerelle student with both
    # catalogs fully selected would trigger via render_export_section().
    xlsx_bytes = generate_excel_download(export_df)
    assert xlsx_bytes[:2] == b"PK"
    roundtrip = pd.read_excel(io.BytesIO(xlsx_bytes), sheet_name="Stundenplan")
    assert len(roundtrip) == len(combined)


def test_ics_export_at_full_scale_tags_every_zusatzmodul_row(bsc_modules, msc_modules):
    combined = list(msc_modules) + list(bsc_modules)
    ics_bytes = generate_ics_download(combined, calendar_name="Testkalender")
    ics_text = ics_bytes.decode("utf-8")

    assert ics_text.count("BEGIN:VEVENT") == len(combined)
    # Every module in bsc_modules is ist_zusatzmodul=True (see
    # test_bsc_vollstaendig_all_rows_tagged_as_zusatzmodul), so the
    # "Zusatzmodul (Passerelle)" description line must appear at least
    # once per Bachelor row's event. DESCRIPTION lines are folded (RFC5545,
    # see export._fold_ics_line) and "\n"-escaped within one folded field,
    # so counting exact occurrences would be fragile - presence is enough
    # to prove the tagging logic actually ran at this scale, not just on
    # the 1-2 row hand-built fixtures in test_export.py.
    assert "Zusatzmodul (Passerelle)" in ics_text


# --- Determinism / reproducibility of the generator ----------------------

def test_generated_fixtures_are_internally_consistent_with_each_other(bsc_modules, msc_modules):
    # Same fictional-name pool feeds both catalogs (see
    # generate_fictional_fixtures.py's _FICTIONAL_FULL_NAMES) - a
    # lecturer name appearing in one fixture is not inherently wrong if
    # it also appears in the other (real lecturers can plausibly teach in
    # both programs), but every name in both must still come from the
    # closed fictional surname pool - a stronger, catalog-spanning version
    # of test_bsc_vollstaendig_no_real_lecturer_names_leaked.
    fictional_surnames = {
        "Muster", "Beispiel", "Demo", "Platzhalter", "Vorlage", "Fiktiv",
        "Testfall", "Musterfrau", "Musterhaft", "Probeweise",
    }
    all_surnames = {
        str(m.dozierende).split(" ")[0]
        for m in list(bsc_modules) + list(msc_modules)
        if m.dozierende and m.dozierende != "N/A"
    }
    assert all_surnames <= fictional_surnames


@pytest.mark.skipif(
    not (REAL_BSC_PATH.exists() and REAL_MSC_PATH.exists()),
    reason="data/real/ (git-ignored) not present on this machine - nothing real to compare against.",
)
def test_no_real_module_identifiers_or_titles_leaked_into_fixtures(bsc_modules, msc_modules):
    """
    Extra safety net beyond the closed-surname-pool checks above: on a
    machine that actually has the real files (e.g. the maintainer's,
    never CI - see data/real/'s own .gitignore), directly diff the real
    Modul-Nr/Kurs-Nr/Anlassbezeichnung values against what ended up in the
    committed fixtures. Skipped everywhere else since there's nothing real
    to compare against - the fixtures' safety doesn't depend on this test
    ever running, it's a belt-and-braces check for whoever regenerates
    them next to a newer real export.
    """
    real_bsc = pd.read_excel(REAL_BSC_PATH, sheet_name="Sheet", header=6)
    real_bsc.columns = [str(c).strip() for c in real_bsc.columns]
    real_msc = pd.read_excel(REAL_MSC_PATH, sheet_name=0, header=2)
    real_msc.columns = [str(c).strip() for c in real_msc.columns]

    real_modul_nrs = set(real_bsc["Modul-Nr."].dropna()) | set(real_msc["Modul-Nr."].dropna())
    real_kurs_nrs = set(real_bsc["Kurs-Nr."].dropna()) | set(real_msc["Kurs-Nr."].dropna())
    real_titles = set(real_bsc["Anlassbezeichnung"].dropna()) | set(real_msc["Anlassbezeichnung"].dropna())

    fictional_modules = list(bsc_modules) + list(msc_modules)
    assert not ({m.modul_nr for m in fictional_modules} & real_modul_nrs)
    assert not ({m.kurs_nr for m in fictional_modules} & real_kurs_nrs)
    assert not ({m.modulname for m in fictional_modules} & real_titles)
